# Generated by Django 4.1 on 2022-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='leaveDiv',
            field=models.CharField(choices=[('FN', 'FN'), ('AN', 'AN'), ('FD', 'FD'), ('None', 'None')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
