# Generated by Django 4.1 on 2022-10-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavemodel_leavediv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='leaveDiv',
            field=models.CharField(max_length=10),
        ),
    ]
