# Generated by Django 4.1 on 2023-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_datanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanalysis',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datanalysis',
            name='day_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datanalysis',
            name='disease',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datanalysis',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datanalysis',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datanalysis',
            name='specialty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datanalysis',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
