# Generated by Django 4.1 on 2022-10-05 16:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('is_asthma', models.BooleanField(default=False)),
                ('is_hypertension', models.BooleanField(default=False)),
                ('is_stroke', models.BooleanField(default=False)),
                ('alergetic_drugs', ckeditor.fields.RichTextField(blank=True, max_length=50)),
                ('weight', models.FloatField(blank=True, default=None)),
                ('height', models.FloatField(blank=True, default=None)),
                ('is_alcoholic', models.BooleanField(default=False)),
                ('symptoms', ckeditor.fields.RichTextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('symptoms', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
