# Generated by Django 4.1 on 2022-10-24 16:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_email', models.EmailField(max_length=100)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('is_asthma', models.BooleanField(default=False)),
                ('is_hypertension', models.BooleanField(default=False)),
                ('is_stroke', models.BooleanField(default=False)),
                ('alergetic_drugs', ckeditor.fields.RichTextField(blank=True, max_length=250)),
                ('weight', models.FloatField(blank=True, default=None)),
                ('height', models.FloatField(blank=True, default=None)),
                ('is_alcoholic', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('symptoms', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=False)),
                ('email', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='email',
        ),
        migrations.DeleteModel(
            name='appointment',
        ),
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
