# Generated by Django 4.1 on 2022-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientappointment_remove_patientdata_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='email',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='doc_email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
