# Generated by Django 4.1 on 2022-11-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patientappointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='timeDiv',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
