# Generated by Django 4.1 on 2023-03-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientdata_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='covid_vacciantion',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_alcoholic',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_asthma',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_diabetic',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_hypertension',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_stroke',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
    ]
