# Generated by Django 4.1 on 2023-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_patientdata_covid_vacciantion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='covid_vacciantion',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_alcoholic',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_asthma',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_diabetic',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_hypertension',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_stroke',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
    ]
