# Generated by Django 4.1 on 2023-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_patientdata_covid_vacciantion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='covid_vacciantion',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_alcoholic',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_asthma',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_diabetic',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='is_stroke',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25),
        ),
    ]
