# Generated by Django 4.1 on 2023-03-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0011_alter_appointment_doc_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentconfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appo_date', models.DateField(default=None)),
                ('appo_time', models.TimeField(default=None)),
                ('appo_status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled'), ('in_progress', 'in_progress')], default='pending', max_length=20)),
                ('payment', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=20)),
                ('doc_email', models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_email', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
