# Generated by Django 4.1 on 2023-03-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appo_id', to='patient.appointmentconfirmation'),
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
