# Generated by Django 4.1 on 2023-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_payment_appo_id_delete_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
