# Generated by Django 4.1 on 2023-03-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_payment_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentconfirmation',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.payment'),
        ),
    ]
