# Generated by Django 4.1 on 2023-03-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_appointmentconfirmation_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientAppointment',
        ),
    ]
