# Generated by Django 4.1 on 2023-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_delete_patientappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconfirmation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
