# Generated by Django 4.1 on 2022-09-17 09:13

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='district',
            field=models.CharField(choices=[('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur'), ('Trivandrum', 'Trivandrum'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Kollam', 'Kollam'), ('Ernakulam', 'Ernakulam'), ('Wayanad', 'Wayanad'), ('Kasaragod', 'Kasaragod'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 9, 17)),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(choices=[('kerala', 'kerala'), ('demo', 'demo'), ('None', 'None')], default='kerala', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='usr_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
