# Generated by Django 4.1 on 2022-10-02 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_demo_alter_account_dob_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.date(2022, 10, 2)),
        ),
    ]
