# Generated by Django 4.1 on 2022-09-07 11:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qual_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BDS', 'BDS'), ('BHMS', 'BHMS'), ('BPT', 'BPT'), ('B.Pharm', 'B.Pharm'), ('BUMS', 'BUMS'), ('MD', 'MD'), ('BYNS', 'BYNS'), ('DS', 'DS'), ('DCM', 'DCM'), ('DPM', 'DPM'), ('D.Pharm', 'D.Pharm'), ('MCM', 'MCM'), ('MMSc', 'MMSc'), ('MPH', 'MPH'), ('MM', 'MM'), ('M.Pharm', 'M.Pharm'), ('M.B.B.S', 'M.B.B.S'), ('M.Phy', 'M.Phy'), ('M.phil', 'M.phil'), ('Msc', 'Msc'), ('MS', 'MS'), ('DNB', 'DNB'), ('M.Ch', 'M.Ch')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
