# Generated by Django 4.1 on 2023-03-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='is_lab_report',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False),
        ),
    ]
