# Generated by Django 4.1 on 2022-09-11 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_doctor_qual_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='des_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='des_name_doctor', to='doctor.designation'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='spec_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_name_related', to='doctor.specialization'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='year_of_service',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
    ]
