# Generated by Django 4.1 on 2022-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_des_name_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='year_of_service',
            field=models.IntegerField(default=2022),
        ),
    ]
