# Generated by Django 4.1 on 2023-03-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='is_lab_report',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100, null=True),
        ),
    ]
