# Generated by Django 4.1 on 2022-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_year_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='year_of_service',
            field=models.IntegerField(),
        ),
    ]
