# Generated by Django 4.1 on 2023-03-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_prescription_is_lab_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='is_lab_report',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100),
        ),
    ]
