# Generated by Django 4.1 on 2023-03-16 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_delete_patientappointment'),
        ('doctor', '0006_alter_prescription_is_lab_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appointmentconfirmation'),
        ),
    ]
