# Generated by Django 4.1 on 2023-03-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_delete_patientappointment'),
        ('doctor', '0007_alter_prescription_appo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appo_id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appoint_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.appointmentconfirmation'),
            preserve_default=False,
        ),
    ]
