# Generated by Django 4.1 on 2023-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_prescription_lab_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='lab_report',
            field=models.CharField(blank=True, choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Stool', 'Stool'), ('Sputum', 'Sputum'), ('X-Ray', 'X-Ray'), ('CT-Scan', 'CT-Scan'), ('MRI', 'MRI'), ('ECG', 'ECG'), ('Ultrasound', 'Ultrasound'), ('Other', 'Other'), ('None', 'None')], max_length=100, null=True),
        ),
    ]
