# Generated by Django 4.1 on 2023-03-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_prescription_lab_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='is_lab_report',
        ),
    ]
