# Generated by Django 4.1 on 2023-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_prescription_lab_uidd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='spec_name',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Gastroenterology', 'Gastroenterology'), ('Dermatology', 'Dermatology'), ('Psychiatry', 'Psychiatry'), ('Nephrology', 'Nephrology'), ('Urology', 'Urology'), ('Oncology', 'Oncology'), ('Radiology', 'Radiology'), ('Anesthesiology', 'Anesthesiology'), ('Dentistry', 'Dentistry'), ('Endocrinology', 'Endocrinology'), ('Gynaecology', 'Gynaecology'), ('Ophthalmology', 'Ophthalmology'), ('Pediatrician', 'Pediatrician'), ('Otolaryngology', 'Otolaryngology'), ('Rheumatology', 'Rheumatology'), ('Dermatology', 'Dermatology'), ('Pulmonology', 'Pulmonology'), ('Plastic Surgery', 'Plastic Surgery'), ('Physician', 'Physician'), ('Physiotherapy', 'Physiotherapy'), ('Psychologist', 'Psychologist'), ('Surgeon', 'Surgeon'), ('ENT', 'ENT'), ('Orthopedics', 'Orthopedics')], max_length=100),
        ),
    ]
