# Generated by Django 4.1 on 2023-03-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_csvdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csvdata',
        ),
    ]
