# Generated by Django 4.1 on 2023-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_labreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='lab_type',
        ),
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress')], default='Pending', max_length=100),
        ),
    ]
