# Generated by Django 4.1 on 2023-03-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_remove_labreport_is_active_remove_labreport_lab_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='status',
        ),
    ]
