# Generated by Django 4.1 on 2023-03-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_remove_labreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='lab_uidd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
