# Generated by Django 4.1 on 2023-03-17 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0007_labreport_lab_uidd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
