# Generated by Django 4.1 on 2023-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_labreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='lab_report/'),
        ),
    ]
