# Generated by Django 4.1 on 2023-03-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_alter_labreport_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='appo_id',
            new_name='appoint_id',
        ),
    ]
