# Generated by Django 4.1 on 2023-03-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_rename_appo_id_labreport_appoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
    ]
